//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChatUser
    {
        public tblChatUser()
        {
            this.tblRoomUsers = new HashSet<tblRoomUser>();
        }
    
        public int IdUser { get; set; }
        public int IdLogin { get; set; }
        public System.Guid ChatUserIdentifier { get; set; }
        public string ChatUserName { get; set; }
        public int IdChatUserStatus { get; set; }
        public Nullable<System.DateTime> LastSeen { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateChange { get; set; }
    
        public virtual tblChatUserStatus tblChatUserStatu { get; set; }
        public virtual tblUserLogin tblUserLogin { get; set; }
        public virtual ICollection<tblRoomUser> tblRoomUsers { get; set; }
    }
}
