//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChatUserStatus
    {
        public tblChatUserStatus()
        {
            this.tblChatUsers = new HashSet<tblChatUser>();
        }
    
        public int IdStatus { get; set; }
        public string StatusName { get; set; }
        public bool MakeOperation { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateChange { get; set; }
    
        public virtual ICollection<tblChatUser> tblChatUsers { get; set; }
    }
}
