//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoomMessageSession
    {
        public int IdSassion { get; set; }
        public int IdRoom { get; set; }
        public System.DateTime SessionStartDate { get; set; }
        public System.DateTime SessionEndDate { get; set; }
        public string SessionMessages { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
    
        public virtual tblChatRoom tblChatRoom { get; set; }
    }
}
