//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoomUser
    {
        public int IdRoom { get; set; }
        public int IdUser { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> DateChange { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual tblChatRoom tblChatRoom { get; set; }
        public virtual tblChatUser tblChatUser { get; set; }
    }
}
